### ISSUE TITLE
Plugin crashes homebridge

### ISSUE THREAD

**Issue by pax0707** [alexp2ad/homebridge-plex-sensors#2]
Homebridge crashes on play.

```

C:\Users\pax07\node_modules\homebridge-plex-sensors\index.js:95
    var event = JSON.parse(json);
                     ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Plex.httpHandler (C:\Users\pax07\node_modules\homebridge-plex-sensors\index.js:95:22)
    at IncomingMessage.request.on.on (C:\Users\pax07\node_modules\homebridge-plex-sensors\index.js:39:16)
    at IncomingMessage.emit (events.js:127:13)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

C:\Users\pax07>
```

**Comment by alexjsp** [comment]
Hmm, interesting. Is your Plex Media Server running on Windows too? I wonder if the Windows file paths are causing an issue in the JSON events sent from the server.

**Comment by pax0707** [comment]
Yes but it looks to me like it could be connected to plex server update.
I'm on plexpass channel.

**Comment by alexjsp** [comment]
Why do you say that, did it work before an update?

**Comment by pax0707** [comment]
Yes.

Didn't occur to me at the time but that day I did update PMS.

**Comment by pax0707** [comment]
Looks like it resolved itself with another Plex server update.
